/* ============================================================
   Mes Listes — base de produits du quotidien v17.8
   Plus de 300 produits organisés par catégorie, avec rayon
   en magasin pour guider dans les grandes enseignes françaises.
   ============================================================ */

const PRODUITS = [

  /* ===== FRUITS & LÉGUMES ===== */
  { id:'p001', nom:'Pommes',            cat:'Fruits & légumes', emoji:'🍎', synonymes:['pomme','golden','granny'], rayon:'Fruits & légumes' },
  { id:'p002', nom:'Bananes',           cat:'Fruits & légumes', emoji:'🍌', synonymes:['banane'], rayon:'Fruits & légumes' },
  { id:'p003', nom:'Oranges',           cat:'Fruits & légumes', emoji:'🍊', synonymes:['orange'], rayon:'Fruits & légumes' },
  { id:'p004', nom:'Citrons',           cat:'Fruits & légumes', emoji:'🍋', synonymes:['citron'], rayon:'Fruits & légumes' },
  { id:'p005', nom:'Fraises',           cat:'Fruits & légumes', emoji:'🍓', synonymes:['fraise'], rayon:'Fruits & légumes' },
  { id:'p006', nom:'Raisins',           cat:'Fruits & légumes', emoji:'🍇', synonymes:['raisin'], rayon:'Fruits & légumes' },
  { id:'p007', nom:'Kiwis',             cat:'Fruits & légumes', emoji:'🥝', synonymes:['kiwi'], rayon:'Fruits & légumes' },
  { id:'p008', nom:'Mangues',           cat:'Fruits & légumes', emoji:'🥭', synonymes:['mangue'], rayon:'Fruits & légumes' },
  { id:'p009', nom:'Avocats',           cat:'Fruits & légumes', emoji:'🥑', synonymes:['avocat'], rayon:'Fruits & légumes' },
  { id:'p010', nom:'Tomates',           cat:'Fruits & légumes', emoji:'🍅', synonymes:['tomate','tomates cerises'], rayon:'Fruits & légumes' },
  { id:'p011', nom:'Carottes',          cat:'Fruits & légumes', emoji:'🥕', synonymes:['carotte'], rayon:'Fruits & légumes' },
  { id:'p012', nom:'Courgettes',        cat:'Fruits & légumes', emoji:'🥒', synonymes:['courgette'], rayon:'Fruits & légumes' },
  { id:'p013', nom:'Oignons',           cat:'Fruits & légumes', emoji:'🧅', synonymes:['oignon','oignons jaunes'], rayon:'Fruits & légumes' },
  { id:'p014', nom:'Ail',               cat:'Fruits & légumes', emoji:'🧄', synonymes:['ail rose','ail blanc'], rayon:'Fruits & légumes' },
  { id:'p015', nom:'Pommes de terre',   cat:'Fruits & légumes', emoji:'🥔', synonymes:['patate','pomme de terre','spunta'], rayon:'Fruits & légumes' },
  { id:'p016', nom:'Poireaux',          cat:'Fruits & légumes', emoji:'🌿', synonymes:['poireau'], rayon:'Fruits & légumes' },
  { id:'p017', nom:'Salade verte',      cat:'Fruits & légumes', emoji:'🥬', synonymes:['salade','laitue','batavia'], rayon:'Fruits & légumes' },
  { id:'p018', nom:'Épinards',          cat:'Fruits & légumes', emoji:'🥬', synonymes:['épinard'], rayon:'Fruits & légumes' },
  { id:'p019', nom:'Haricots verts',    cat:'Fruits & légumes', emoji:'🫘', synonymes:['haricot vert'], rayon:'Fruits & légumes' },
  { id:'p020', nom:'Brocolis',          cat:'Fruits & légumes', emoji:'🥦', synonymes:['brocoli','broccoli'], rayon:'Fruits & légumes' },
  { id:'p021', nom:'Chou-fleur',        cat:'Fruits & légumes', emoji:'🥦', synonymes:['choufleur'], rayon:'Fruits & légumes' },
  { id:'p022', nom:'Champignons',       cat:'Fruits & légumes', emoji:'🍄', synonymes:['champignon de Paris'], rayon:'Fruits & légumes' },
  { id:'p023', nom:'Poivrons',          cat:'Fruits & légumes', emoji:'🫑', synonymes:['poivron rouge','poivron vert'], rayon:'Fruits & légumes' },
  { id:'p024', nom:'Aubergines',        cat:'Fruits & légumes', emoji:'🍆', synonymes:['aubergine'], rayon:'Fruits & légumes' },
  { id:'p025', nom:'Poires',            cat:'Fruits & légumes', emoji:'🍐', synonymes:['poire','williams','conférence'], rayon:'Fruits & légumes' },
  { id:'p026', nom:'Pêches',            cat:'Fruits & légumes', emoji:'🍑', synonymes:['pêche','brugnon','nectarine'], rayon:'Fruits & légumes' },
  { id:'p027', nom:'Cerises',           cat:'Fruits & légumes', emoji:'🍒', synonymes:['cerise'], rayon:'Fruits & légumes' },
  { id:'p028', nom:'Pastèque',          cat:'Fruits & légumes', emoji:'🍉', synonymes:['pasteque'], rayon:'Fruits & légumes' },
  { id:'p029', nom:'Melon',             cat:'Fruits & légumes', emoji:'🍈', synonymes:['melon charentais'], rayon:'Fruits & légumes' },
  { id:'p030', nom:'Ananas',            cat:'Fruits & légumes', emoji:'🍍', synonymes:[], rayon:'Fruits & légumes' },
  { id:'p031', nom:'Céleri',            cat:'Fruits & légumes', emoji:'🥦', synonymes:['céleri-rave','céleri branche'], rayon:'Fruits & légumes' },
  { id:'p032', nom:'Betteraves',        cat:'Fruits & légumes', emoji:'🫚', synonymes:['betterave rouge','betterave cuite'], rayon:'Fruits & légumes' },
  { id:'p033', nom:'Concombre',         cat:'Fruits & légumes', emoji:'🥒', synonymes:[], rayon:'Fruits & légumes' },
  { id:'p034', nom:'Radis',             cat:'Fruits & légumes', emoji:'🌱', synonymes:['botte de radis'], rayon:'Fruits & légumes' },

  /* ===== VIANDE & POISSON ===== */
  { id:'p035', nom:'Poulet entier',          cat:'Viande & poisson', emoji:'🍗', synonymes:['poulet rôti'], rayon:'Boucherie' },
  { id:'p036', nom:'Blancs de poulet',       cat:'Viande & poisson', emoji:'🍗', synonymes:['blanc de poulet','filet de poulet'], rayon:'Boucherie' },
  { id:'p037', nom:'Cuisses de poulet',      cat:'Viande & poisson', emoji:'🍗', synonymes:['cuisse de poulet'], rayon:'Boucherie' },
  { id:'p038', nom:'Escalopes de dinde',     cat:'Viande & poisson', emoji:'🦃', synonymes:['dinde','escalope de dinde'], rayon:'Boucherie' },
  { id:'p039', nom:'Bœuf haché',             cat:'Viande & poisson', emoji:'🥩', synonymes:['steak haché','viande hachée'], rayon:'Boucherie' },
  { id:'p040', nom:'Steaks de bœuf',         cat:'Viande & poisson', emoji:'🥩', synonymes:['steak','entrecôte','faux-filet'], rayon:'Boucherie' },
  { id:'p041', nom:'Rôti de bœuf',           cat:'Viande & poisson', emoji:'🥩', synonymes:['rôti'], rayon:'Boucherie' },
  { id:'p042', nom:'Côtelettes de porc',     cat:'Viande & poisson', emoji:'🥩', synonymes:['côtelette','côte de porc'], rayon:'Boucherie' },
  { id:'p043', nom:'Lardons',                cat:'Viande & poisson', emoji:'🥓', synonymes:['lardon fumé'], rayon:'Charcuterie' },
  { id:'p044', nom:'Jambon blanc',           cat:'Viande & poisson', emoji:'🥓', synonymes:['jambon cuit','jambon Paris'], rayon:'Charcuterie' },
  { id:'p045', nom:'Jambon de Bayonne',      cat:'Viande & poisson', emoji:'🥓', synonymes:['jambon cru','jambon sec'], rayon:'Charcuterie' },
  { id:'p046', nom:'Saucisses',              cat:'Viande & poisson', emoji:'🌭', synonymes:['chipolata','merguez','saucisse de Francfort'], rayon:'Boucherie' },
  { id:'p047', nom:'Saumon frais',           cat:'Viande & poisson', emoji:'🐟', synonymes:['pavé de saumon','filet de saumon'], rayon:'Poissonnerie' },
  { id:'p048', nom:'Cabillaud',              cat:'Viande & poisson', emoji:'🐟', synonymes:['morue fraîche','dos de cabillaud'], rayon:'Poissonnerie' },
  { id:'p049', nom:'Crevettes',             cat:'Viande & poisson', emoji:'🦐', synonymes:['crevette rose','gambas'], rayon:'Poissonnerie' },
  { id:'p050', nom:'Moules',                cat:'Viande & poisson', emoji:'🦪', synonymes:['moule de bouchot'], rayon:'Poissonnerie' },
  { id:'p051', nom:'Agneau (gigot)',         cat:'Viande & poisson', emoji:'🥩', synonymes:['gigot','épaule d\'agneau'], rayon:'Boucherie' },
  { id:'p052', nom:'Canard (magret)',        cat:'Viande & poisson', emoji:'🦆', synonymes:['magret de canard','magret'], rayon:'Boucherie' },
  { id:'p053', nom:'Veau (escalope)',        cat:'Viande & poisson', emoji:'🥩', synonymes:['veau','escalope de veau'], rayon:'Boucherie' },
  { id:'p054', nom:'Lieu noir',             cat:'Viande & poisson', emoji:'🐟', synonymes:['lieu'], rayon:'Poissonnerie' },
  { id:'p055', nom:'Thon frais',            cat:'Viande & poisson', emoji:'🐟', synonymes:['steak de thon'], rayon:'Poissonnerie' },

  /* ===== CRÉMERIE & ŒUFS ===== */
  { id:'p056', nom:'Lait demi-écrémé',     cat:'Crémerie', emoji:'🥛', synonymes:['lait','lait 1/2 écrémé'], rayon:'Crémerie' },
  { id:'p057', nom:'Lait entier',          cat:'Crémerie', emoji:'🥛', synonymes:[], rayon:'Crémerie' },
  { id:'p058', nom:'Lait végétal avoine',  cat:'Crémerie', emoji:'🥛', synonymes:['oat milk','avoine'], rayon:'Crémerie' },
  { id:'p059', nom:'Lait végétal amande',  cat:'Crémerie', emoji:'🥛', synonymes:['amande'], rayon:'Crémerie' },
  { id:'p060', nom:'Beurre doux',          cat:'Crémerie', emoji:'🧈', synonymes:['beurre'], rayon:'Crémerie' },
  { id:'p061', nom:'Beurre demi-sel',      cat:'Crémerie', emoji:'🧈', synonymes:['beurre salé'], rayon:'Crémerie' },
  { id:'p062', nom:'Crème fraîche épaisse',cat:'Crémerie', emoji:'🥛', synonymes:['crème fraîche','crème épaisse'], rayon:'Crémerie' },
  { id:'p063', nom:'Crème liquide entière',cat:'Crémerie', emoji:'🥛', synonymes:['crème liquide','crème fleurette'], rayon:'Crémerie' },
  { id:'p064', nom:'Emmental râpé',        cat:'Crémerie', emoji:'🧀', synonymes:['fromage râpé','gruyère'], rayon:'Crémerie' },
  { id:'p065', nom:'Camembert',            cat:'Crémerie', emoji:'🧀', synonymes:[], rayon:'Crémerie' },
  { id:'p066', nom:'Brie',                 cat:'Crémerie', emoji:'🧀', synonymes:['brie de Meaux'], rayon:'Crémerie' },
  { id:'p067', nom:'Comté',               cat:'Crémerie', emoji:'🧀', synonymes:[], rayon:'Crémerie' },
  { id:'p068', nom:'Mozzarella',           cat:'Crémerie', emoji:'🧀', synonymes:[], rayon:'Crémerie' },
  { id:'p069', nom:'Fromage de chèvre',   cat:'Crémerie', emoji:'🧀', synonymes:['chèvre','bûchette'], rayon:'Crémerie' },
  { id:'p070', nom:'Roquefort',            cat:'Crémerie', emoji:'🧀', synonymes:['bleu','fourme'], rayon:'Crémerie' },
  { id:'p071', nom:'Parmesan',             cat:'Crémerie', emoji:'🧀', synonymes:[], rayon:'Crémerie' },
  { id:'p072', nom:'Yaourts nature',       cat:'Crémerie', emoji:'🥛', synonymes:['yaourt','yaourt nature'], rayon:'Crémerie' },
  { id:'p073', nom:'Yaourts aux fruits',   cat:'Crémerie', emoji:'🍓', synonymes:['yaourt fruité'], rayon:'Crémerie' },
  { id:'p074', nom:'Fromage blanc',        cat:'Crémerie', emoji:'🥛', synonymes:['faisselle','skyr'], rayon:'Crémerie' },
  { id:'p075', nom:'Œufs (boîte de 6)',    cat:'Crémerie', emoji:'🥚', synonymes:['œuf','oeufs','6 œufs'], rayon:'Crémerie' },
  { id:'p076', nom:'Œufs (boîte de 12)',   cat:'Crémerie', emoji:'🥚', synonymes:['12 œufs','boîte œufs'], rayon:'Crémerie' },
  { id:'p077', nom:'Crème dessert',        cat:'Crémerie', emoji:'🍮', synonymes:['danette','crème dessert chocolat'], rayon:'Crémerie' },
  { id:'p078', nom:'Margarine',            cat:'Crémerie', emoji:'🧈', synonymes:['flora'], rayon:'Crémerie' },

  /* ===== BOULANGERIE ===== */
  { id:'p079', nom:'Pain de mie',          cat:'Boulangerie', emoji:'🍞', synonymes:['pain de mie tranché'], rayon:'Boulangerie' },
  { id:'p080', nom:'Baguette',             cat:'Boulangerie', emoji:'🥖', synonymes:['baguette tradition'], rayon:'Boulangerie' },
  { id:'p081', nom:'Pain complet',         cat:'Boulangerie', emoji:'🍞', synonymes:['pain aux céréales','pain de seigle'], rayon:'Boulangerie' },
  { id:'p082', nom:'Biscottes',            cat:'Boulangerie', emoji:'🍞', synonymes:['biscotte'], rayon:'Épicerie' },
  { id:'p083', nom:'Croissants',           cat:'Boulangerie', emoji:'🥐', synonymes:['croissant'], rayon:'Boulangerie' },
  { id:'p084', nom:'Pains au chocolat',    cat:'Boulangerie', emoji:'🥐', synonymes:['pain au chocolat','chocolatine'], rayon:'Boulangerie' },
  { id:'p085', nom:'Pain burger',          cat:'Boulangerie', emoji:'🍔', synonymes:['bun','pain hamburger','pain brioche'], rayon:'Boulangerie' },
  { id:'p086', nom:'Tortillas (wraps)',    cat:'Boulangerie', emoji:'🫓', synonymes:['wrap','tortilla','galette'], rayon:'Épicerie' },
  { id:'p087', nom:'Brioches',             cat:'Boulangerie', emoji:'🍞', synonymes:['brioche','tresse'], rayon:'Boulangerie' },
  { id:'p088', nom:'Pain pita',            cat:'Boulangerie', emoji:'🫓', synonymes:['pita'], rayon:'Boulangerie' },
  { id:'p089', nom:'Pains suédois',        cat:'Boulangerie', emoji:'🍞', synonymes:['wasa','pain grillé'], rayon:'Épicerie' },
  { id:'p090', nom:'Naan',                 cat:'Boulangerie', emoji:'🫓', synonymes:['pain naan','pains naan'], rayon:'Épicerie' },

  /* ===== ÉPICERIE SUCRÉE ===== */
  { id:'p091', nom:'Sucre en poudre',      cat:'Épicerie sucrée', emoji:'🍬', synonymes:['sucre blanc','sucre'], rayon:'Épicerie' },
  { id:'p092', nom:'Cassonade',            cat:'Épicerie sucrée', emoji:'🍬', synonymes:['sucre roux','vergeoise'], rayon:'Épicerie' },
  { id:'p093', nom:'Sucre glace',          cat:'Épicerie sucrée', emoji:'🍬', synonymes:[], rayon:'Épicerie' },
  { id:'p094', nom:'Confiture de fraises', cat:'Épicerie sucrée', emoji:'🍓', synonymes:['confiture'], rayon:'Épicerie' },
  { id:'p095', nom:'Confiture d\'abricots',cat:'Épicerie sucrée', emoji:'🍑', synonymes:['confiture abricot'], rayon:'Épicerie' },
  { id:'p096', nom:'Miel',                 cat:'Épicerie sucrée', emoji:'🍯', synonymes:['miel d\'acacia','miel toutes fleurs'], rayon:'Épicerie' },
  { id:'p097', nom:'Nutella',              cat:'Épicerie sucrée', emoji:'🍫', synonymes:['pâte à tartiner'], rayon:'Épicerie' },
  { id:'p098', nom:'Chocolat noir',        cat:'Épicerie sucrée', emoji:'🍫', synonymes:['tablette noir','chocolat à croquer'], rayon:'Épicerie' },
  { id:'p099', nom:'Chocolat au lait',     cat:'Épicerie sucrée', emoji:'🍫', synonymes:['tablette lait'], rayon:'Épicerie' },
  { id:'p100', nom:'Chocolat blanc',       cat:'Épicerie sucrée', emoji:'🍫', synonymes:['tablette blanc'], rayon:'Épicerie' },
  { id:'p101', nom:'Céréales',             cat:'Épicerie sucrée', emoji:'🥣', synonymes:['corn flakes','frosties','honey pops'], rayon:'Épicerie' },
  { id:'p102', nom:'Flocons d\'avoine',    cat:'Épicerie sucrée', emoji:'🥣', synonymes:['porridge','avoine'], rayon:'Épicerie' },
  { id:'p103', nom:'Granola muesli',       cat:'Épicerie sucrée', emoji:'🥣', synonymes:['muesli','granola'], rayon:'Épicerie' },
  { id:'p104', nom:'Biscuits sablés',      cat:'Épicerie sucrée', emoji:'🍪', synonymes:['petits beurre','sablé'], rayon:'Épicerie' },
  { id:'p105', nom:'Biscuits chocolatés',  cat:'Épicerie sucrée', emoji:'🍪', synonymes:['prince','oreo','lu'], rayon:'Épicerie' },
  { id:'p106', nom:'Madeleines',           cat:'Épicerie sucrée', emoji:'🧇', synonymes:['madeleine'], rayon:'Épicerie' },
  { id:'p107', nom:'Speculoos',            cat:'Épicerie sucrée', emoji:'🍪', synonymes:['spéculoos','lotus'], rayon:'Épicerie' },
  { id:'p108', nom:'Chocolat pâtissier',   cat:'Épicerie sucrée', emoji:'🍫', synonymes:['chocolat à cuire','nestlé dessert'], rayon:'Épicerie' },
  { id:'p109', nom:'Levure chimique',      cat:'Épicerie sucrée', emoji:'🧁', synonymes:['poudre à lever','levure pâtissière'], rayon:'Épicerie' },
  { id:'p110', nom:'Sirop de grenadine',   cat:'Épicerie sucrée', emoji:'🍹', synonymes:['grenadine','sirop'], rayon:'Épicerie' },
  { id:'p111', nom:'Bonbons',              cat:'Épicerie sucrée', emoji:'🍬', synonymes:['carambar','chewing-gum','bonbon'], rayon:'Épicerie' },
  { id:'p112', nom:'Poudre d\'amandes',    cat:'Épicerie sucrée', emoji:'🥜', synonymes:['amandes en poudre'], rayon:'Épicerie' },
  { id:'p113', nom:'Vanille',              cat:'Épicerie sucrée', emoji:'🌿', synonymes:['gousse vanille','extrait vanille'], rayon:'Épicerie' },

  /* ===== ÉPICERIE SALÉE ===== */
  { id:'p114', nom:'Pâtes spaghetti',      cat:'Épicerie salée', emoji:'🍝', synonymes:['spaghetti','pâtes longues'], rayon:'Épicerie' },
  { id:'p115', nom:'Pâtes penne',          cat:'Épicerie salée', emoji:'🍝', synonymes:['penne','rigatoni'], rayon:'Épicerie' },
  { id:'p116', nom:'Pâtes tagliatelles',   cat:'Épicerie salée', emoji:'🍝', synonymes:['tagliatelle','linguine'], rayon:'Épicerie' },
  { id:'p117', nom:'Riz blanc',            cat:'Épicerie salée', emoji:'🍚', synonymes:['riz long','riz'], rayon:'Épicerie' },
  { id:'p118', nom:'Riz basmati',          cat:'Épicerie salée', emoji:'🍚', synonymes:['basmati'], rayon:'Épicerie' },
  { id:'p119', nom:'Farine blanche',       cat:'Épicerie salée', emoji:'🌾', synonymes:['farine T45','farine T55','farine'], rayon:'Épicerie' },
  { id:'p120', nom:'Semoule',              cat:'Épicerie salée', emoji:'🌾', synonymes:['couscous','semoule de blé'], rayon:'Épicerie' },
  { id:'p121', nom:'Quinoa',              cat:'Épicerie salée', emoji:'🌾', synonymes:[], rayon:'Épicerie' },
  { id:'p122', nom:'Boulgour',             cat:'Épicerie salée', emoji:'🌾', synonymes:['blé dur'], rayon:'Épicerie' },
  { id:'p123', nom:'Lentilles sèches',     cat:'Épicerie salée', emoji:'🫘', synonymes:['lentille verte','lentille corail'], rayon:'Épicerie' },
  { id:'p124', nom:'Sel fin',              cat:'Épicerie salée', emoji:'🧂', synonymes:['sel'], rayon:'Épicerie' },
  { id:'p125', nom:'Gros sel',             cat:'Épicerie salée', emoji:'🧂', synonymes:['sel de Guérande','fleur de sel'], rayon:'Épicerie' },
  { id:'p126', nom:'Poivre',              cat:'Épicerie salée', emoji:'🌶️', synonymes:['poivre noir','poivre moulu'], rayon:'Épicerie' },
  { id:'p127', nom:'Huile d\'olive',       cat:'Épicerie salée', emoji:'🫙', synonymes:['huile olive'], rayon:'Épicerie' },
  { id:'p128', nom:'Huile de tournesol',   cat:'Épicerie salée', emoji:'🫙', synonymes:['huile tournesol'], rayon:'Épicerie' },
  { id:'p129', nom:'Vinaigre blanc',       cat:'Épicerie salée', emoji:'🫙', synonymes:['vinaigre'], rayon:'Épicerie' },
  { id:'p130', nom:'Vinaigre balsamique',  cat:'Épicerie salée', emoji:'🫙', synonymes:['balsamique'], rayon:'Épicerie' },
  { id:'p131', nom:'Moutarde',             cat:'Épicerie salée', emoji:'🫙', synonymes:['moutarde de Dijon','moutarde forte'], rayon:'Épicerie' },
  { id:'p132', nom:'Mayonnaise',           cat:'Épicerie salée', emoji:'🫙', synonymes:['mayo'], rayon:'Épicerie' },
  { id:'p133', nom:'Ketchup',              cat:'Épicerie salée', emoji:'🫙', synonymes:[], rayon:'Épicerie' },
  { id:'p134', nom:'Sauce tomate',         cat:'Épicerie salée', emoji:'🍅', synonymes:['coulis de tomates','coulis'], rayon:'Épicerie' },
  { id:'p135', nom:'Tomates concassées',   cat:'Épicerie salée', emoji:'🍅', synonymes:['tomates pelées','tomates en boîte'], rayon:'Conserves' },
  { id:'p136', nom:'Maïs en boîte',        cat:'Épicerie salée', emoji:'🌽', synonymes:['maïs doux'], rayon:'Conserves' },
  { id:'p137', nom:'Haricots rouges',      cat:'Épicerie salée', emoji:'🫘', synonymes:['haricots en boîte','pois chiches'], rayon:'Conserves' },
  { id:'p138', nom:'Lentilles en boîte',   cat:'Épicerie salée', emoji:'🫘', synonymes:['lentilles cuites'], rayon:'Conserves' },
  { id:'p139', nom:'Thon en boîte',        cat:'Épicerie salée', emoji:'🐟', synonymes:['thon naturel','thon à l\'huile'], rayon:'Conserves' },
  { id:'p140', nom:'Sardines en boîte',    cat:'Épicerie salée', emoji:'🐟', synonymes:['sardines'], rayon:'Conserves' },
  { id:'p141', nom:'Bouillon de légumes',  cat:'Épicerie salée', emoji:'🍲', synonymes:['cube légumes','bouillon cube'], rayon:'Épicerie' },
  { id:'p142', nom:'Bouillon de poulet',   cat:'Épicerie salée', emoji:'🍲', synonymes:['cube poulet'], rayon:'Épicerie' },
  { id:'p143', nom:'Soupe en brique',      cat:'Épicerie salée', emoji:'🍲', synonymes:['velouté','gazpacho'], rayon:'Épicerie' },
  { id:'p144', nom:'Sauce béchamel',       cat:'Épicerie salée', emoji:'🫙', synonymes:['béchamel'], rayon:'Épicerie' },
  { id:'p145', nom:'Sauce soja',           cat:'Épicerie salée', emoji:'🫙', synonymes:['soja','tamari'], rayon:'Épicerie' },
  { id:'p146', nom:'Lait de coco',         cat:'Épicerie salée', emoji:'🥥', synonymes:['lait coco','crème de coco'], rayon:'Épicerie' },
  { id:'p147', nom:'Curry en poudre',      cat:'Épicerie salée', emoji:'🌶️', synonymes:['curry'], rayon:'Épicerie' },
  { id:'p148', nom:'Paprika',              cat:'Épicerie salée', emoji:'🌶️', synonymes:['paprika doux','paprika fumé'], rayon:'Épicerie' },
  { id:'p149', nom:'Herbes de Provence',   cat:'Épicerie salée', emoji:'🌿', synonymes:['thym','romarin','herbes aromatiques'], rayon:'Épicerie' },
  { id:'p150', nom:'Chips',               cat:'Épicerie salée', emoji:'🥔', synonymes:['chips apéritif','tuiles'], rayon:'Épicerie' },
  { id:'p151', nom:'Crackers apéritif',    cat:'Épicerie salée', emoji:'🧀', synonymes:['gressins','toast'], rayon:'Épicerie' },
  { id:'p152', nom:'Olives',              cat:'Épicerie salée', emoji:'🫒', synonymes:['olive verte','olive noire','tapenade'], rayon:'Épicerie' },
  { id:'p153', nom:'Polenta',             cat:'Épicerie salée', emoji:'🌽', synonymes:['semoule de maïs'], rayon:'Épicerie' },

  /* ===== BOISSONS ===== */
  { id:'p154', nom:'Eau plate (pack)',     cat:'Boissons', emoji:'💧', synonymes:['eau','evian','volvic','cristalline'], rayon:'Boissons' },
  { id:'p155', nom:'Eau gazeuse',          cat:'Boissons', emoji:'💧', synonymes:['pétillante','perrier','san pellegrino'], rayon:'Boissons' },
  { id:'p156', nom:'Jus d\'orange',        cat:'Boissons', emoji:'🍊', synonymes:['jus orange','jus d\'orange pressé'], rayon:'Boissons' },
  { id:'p157', nom:'Jus de pomme',         cat:'Boissons', emoji:'🍎', synonymes:['jus pomme'], rayon:'Boissons' },
  { id:'p158', nom:'Nectar de pêche',      cat:'Boissons', emoji:'🍑', synonymes:['nectar','jus pêche'], rayon:'Boissons' },
  { id:'p159', nom:'Coca-Cola',            cat:'Boissons', emoji:'🥤', synonymes:['coca','soda','pepsi'], rayon:'Boissons' },
  { id:'p160', nom:'Limonade',             cat:'Boissons', emoji:'🥤', synonymes:['schweppes','tonic'], rayon:'Boissons' },
  { id:'p161', nom:'Bière blonde',         cat:'Boissons', emoji:'🍺', synonymes:['bière','kronenbourg','heineken','1664'], rayon:'Boissons' },
  { id:'p162', nom:'Cidre',               cat:'Boissons', emoji:'🍺', synonymes:['cidre brut','cidre doux'], rayon:'Boissons' },
  { id:'p163', nom:'Vin rouge',            cat:'Boissons', emoji:'🍷', synonymes:['rouge','bordeaux','côtes du rhône'], rayon:'Vins & Spiritueux' },
  { id:'p164', nom:'Vin blanc',            cat:'Boissons', emoji:'🥂', synonymes:['blanc sec','chardonnay','muscadet'], rayon:'Vins & Spiritueux' },
  { id:'p165', nom:'Vin rosé',             cat:'Boissons', emoji:'🥂', synonymes:['rosé'], rayon:'Vins & Spiritueux' },
  { id:'p166', nom:'Champagne',            cat:'Boissons', emoji:'🍾', synonymes:['mousseux','crémant','prosecco'], rayon:'Vins & Spiritueux' },
  { id:'p167', nom:'Café moulu',           cat:'Boissons', emoji:'☕', synonymes:['café','expresso'], rayon:'Épicerie' },
  { id:'p168', nom:'Café en dosettes',     cat:'Boissons', emoji:'☕', synonymes:['nespresso','capsule café','dosette'], rayon:'Épicerie' },
  { id:'p169', nom:'Thé noir',             cat:'Boissons', emoji:'🍵', synonymes:['thé','earl grey','english breakfast'], rayon:'Épicerie' },
  { id:'p170', nom:'Tisane',               cat:'Boissons', emoji:'🍵', synonymes:['infusion','camomille','verveine'], rayon:'Épicerie' },
  { id:'p171', nom:'Chocolat chaud',       cat:'Boissons', emoji:'🍫', synonymes:['poudre chocolat','nesquik','ovomaltine'], rayon:'Épicerie' },
  { id:'p172', nom:'Kombucha',             cat:'Boissons', emoji:'🫙', synonymes:[], rayon:'Boissons' },

  /* ===== SURGELÉS ===== */
  { id:'p173', nom:'Pizza surgelée',       cat:'Surgelés', emoji:'🍕', synonymes:['pizza','pizza congelée'], rayon:'Surgelés' },
  { id:'p174', nom:'Steaks hachés surgelés',cat:'Surgelés',emoji:'🍔', synonymes:['steak congelé'], rayon:'Surgelés' },
  { id:'p175', nom:'Frites surgelées',     cat:'Surgelés', emoji:'🍟', synonymes:['frites'], rayon:'Surgelés' },
  { id:'p176', nom:'Légumes surgelés',     cat:'Surgelés', emoji:'🥦', synonymes:['légumes congelés','jardinière','poêlée'], rayon:'Surgelés' },
  { id:'p177', nom:'Épinards surgelés',    cat:'Surgelés', emoji:'🥬', synonymes:['épinards congelés'], rayon:'Surgelés' },
  { id:'p178', nom:'Petits pois surgelés', cat:'Surgelés', emoji:'🟢', synonymes:['petits pois'], rayon:'Surgelés' },
  { id:'p179', nom:'Glace vanille',        cat:'Surgelés', emoji:'🍦', synonymes:['glace','crème glacée'], rayon:'Surgelés' },
  { id:'p180', nom:'Sorbet fruits rouges', cat:'Surgelés', emoji:'🍧', synonymes:['sorbet'], rayon:'Surgelés' },
  { id:'p181', nom:'Poisson pané',         cat:'Surgelés', emoji:'🐟', synonymes:['fish sticks','bâtonnet poisson'], rayon:'Surgelés' },
  { id:'p182', nom:'Nuggets de poulet',    cat:'Surgelés', emoji:'🍗', synonymes:['nuggets'], rayon:'Surgelés' },
  { id:'p183', nom:'Crevettes surgelées',  cat:'Surgelés', emoji:'🦐', synonymes:['crevettes congelées'], rayon:'Surgelés' },
  { id:'p184', nom:'Lasagnes surgelées',   cat:'Surgelés', emoji:'🍝', synonymes:['lasagnes','plat cuisiné surgelé'], rayon:'Surgelés' },
  { id:'p185', nom:'Quiche surgelée',      cat:'Surgelés', emoji:'🥧', synonymes:['quiche lorraine'], rayon:'Surgelés' },
  { id:'p186', nom:'Crêpes surgelées',     cat:'Surgelés', emoji:'🥞', synonymes:['crêpe'], rayon:'Surgelés' },

  /* ===== HYGIÈNE & BEAUTÉ ===== */
  { id:'p187', nom:'Shampooing',           cat:'Hygiène & beauté', emoji:'🧴', synonymes:['shampoing'], rayon:'Hygiène / Beauté' },
  { id:'p188', nom:'Après-shampooing',     cat:'Hygiène & beauté', emoji:'🧴', synonymes:['conditionneur','soin'], rayon:'Hygiène / Beauté' },
  { id:'p189', nom:'Gel douche',           cat:'Hygiène & beauté', emoji:'🚿', synonymes:['douche','gel corps'], rayon:'Hygiène / Beauté' },
  { id:'p190', nom:'Savon liquide',        cat:'Hygiène & beauté', emoji:'🧼', synonymes:['savon mains'], rayon:'Hygiène / Beauté' },
  { id:'p191', nom:'Savon solide',         cat:'Hygiène & beauté', emoji:'🧼', synonymes:['pain de savon','savonnette'], rayon:'Hygiène / Beauté' },
  { id:'p192', nom:'Dentifrice',           cat:'Hygiène & beauté', emoji:'🦷', synonymes:['pâte dentifrice','colgate','signal'], rayon:'Hygiène / Beauté' },
  { id:'p193', nom:'Brosse à dents',       cat:'Hygiène & beauté', emoji:'🪥', synonymes:[], rayon:'Hygiène / Beauté' },
  { id:'p194', nom:'Fil dentaire',         cat:'Hygiène & beauté', emoji:'🦷', synonymes:[], rayon:'Hygiène / Beauté' },
  { id:'p195', nom:'Bain de bouche',       cat:'Hygiène & beauté', emoji:'💧', synonymes:['rince-bouche','listerine'], rayon:'Hygiène / Beauté' },
  { id:'p196', nom:'Déodorant',            cat:'Hygiène & beauté', emoji:'🌸', synonymes:['anti-transpirant','déo','déodorant roll-on'], rayon:'Hygiène / Beauté' },
  { id:'p197', nom:'Rasoir',               cat:'Hygiène & beauté', emoji:'🪒', synonymes:['rasoir jetable','gillette'], rayon:'Hygiène / Beauté' },
  { id:'p198', nom:'Mousse à raser',       cat:'Hygiène & beauté', emoji:'🪒', synonymes:['gel à raser','crème à raser'], rayon:'Hygiène / Beauté' },
  { id:'p199', nom:'Crème hydratante',     cat:'Hygiène & beauté', emoji:'💆', synonymes:['crème visage','moisturizer'], rayon:'Hygiène / Beauté' },
  { id:'p200', nom:'Crème corps',          cat:'Hygiène & beauté', emoji:'🧴', synonymes:['lait corps','lotion'], rayon:'Hygiène / Beauté' },
  { id:'p201', nom:'Eau micellaire',       cat:'Hygiène & beauté', emoji:'💧', synonymes:['démaquillant','lait démaquillant'], rayon:'Hygiène / Beauté' },
  { id:'p202', nom:'Coton démaquillant',   cat:'Hygiène & beauté', emoji:'🌸', synonymes:['disques coton','coton'], rayon:'Hygiène / Beauté' },
  { id:'p203', nom:'Cotons-tiges',         cat:'Hygiène & beauté', emoji:'🦻', synonymes:['coton-tige'], rayon:'Hygiène / Beauté' },
  { id:'p204', nom:'Protections hygiéniques',cat:'Hygiène & beauté',emoji:'🌸',synonymes:['serviettes hygiéniques','tampons','protège-slips'], rayon:'Hygiène / Beauté' },
  { id:'p205', nom:'Crème solaire',        cat:'Hygiène & beauté', emoji:'☀️', synonymes:['écran solaire','SPF','sunscreen'], rayon:'Hygiène / Beauté' },
  { id:'p206', nom:'Masque cheveux',       cat:'Hygiène & beauté', emoji:'🧴', synonymes:['soin cheveux','masque capillaire'], rayon:'Hygiène / Beauté' },
  { id:'p207', nom:'Mascara',              cat:'Hygiène & beauté', emoji:'💄', synonymes:['maquillage','rimmel'], rayon:'Hygiène / Beauté' },
  { id:'p208', nom:'Vernis à ongles',      cat:'Hygiène & beauté', emoji:'💅', synonymes:['vernis'], rayon:'Hygiène / Beauté' },

  /* ===== ENTRETIEN & NETTOYAGE ===== */
  { id:'p209', nom:'Lessive liquide',      cat:'Entretien', emoji:'🧹', synonymes:['lessive machine','persil','ariel'], rayon:'Entretien' },
  { id:'p210', nom:'Lessive en capsules',  cat:'Entretien', emoji:'🧹', synonymes:['pods','capsules lessive','dosettes lessive'], rayon:'Entretien' },
  { id:'p211', nom:'Adoucissant',          cat:'Entretien', emoji:'🌸', synonymes:['assouplissant','lenor'], rayon:'Entretien' },
  { id:'p212', nom:'Liquide vaisselle',    cat:'Entretien', emoji:'🍽️', synonymes:['produit vaisselle','fairy'], rayon:'Entretien' },
  { id:'p213', nom:'Tablettes lave-vaisselle',cat:'Entretien',emoji:'🍽️',synonymes:['pastilles lave-vaisselle','finish'], rayon:'Entretien' },
  { id:'p214', nom:'Nettoyant multi-surfaces',cat:'Entretien',emoji:'🧽',synonymes:['spray nettoyant','ajax','cif'], rayon:'Entretien' },
  { id:'p215', nom:'Eau de javel',         cat:'Entretien', emoji:'🧴', synonymes:['javel','eau javel'], rayon:'Entretien' },
  { id:'p216', nom:'Nettoyant WC',         cat:'Entretien', emoji:'🚽', synonymes:['canard WC','WC net','détartrant'], rayon:'Entretien' },
  { id:'p217', nom:'Nettoyant vitre',      cat:'Entretien', emoji:'🪟', synonymes:['produit vitres','windex'], rayon:'Entretien' },
  { id:'p218', nom:'Sacs poubelle',        cat:'Entretien', emoji:'🗑️', synonymes:['sac-poubelle','sac poubelle 30L'], rayon:'Entretien' },
  { id:'p219', nom:'Éponges',              cat:'Entretien', emoji:'🧽', synonymes:['éponge grattante','scotch-brite'], rayon:'Entretien' },
  { id:'p220', nom:'Essuie-tout',          cat:'Entretien', emoji:'🧻', synonymes:['sopalin','papier ménager'], rayon:'Entretien' },
  { id:'p221', nom:'Papier toilette',      cat:'Entretien', emoji:'🧻', synonymes:['PQ','papier hygiénique','lotus'], rayon:'Entretien' },
  { id:'p222', nom:'Mouchoirs en papier',  cat:'Entretien', emoji:'🤧', synonymes:['kleenex','mouchoirs papier'], rayon:'Entretien' },
  { id:'p223', nom:'Sacs congélation',     cat:'Entretien', emoji:'🧊', synonymes:['sac zip','sac congel'], rayon:'Entretien' },
  { id:'p224', nom:'Film alimentaire',     cat:'Entretien', emoji:'🎁', synonymes:['film étirable','cellophane'], rayon:'Entretien' },
  { id:'p225', nom:'Papier aluminium',     cat:'Entretien', emoji:'✨', synonymes:['alu','papier alu'], rayon:'Entretien' },
  { id:'p226', nom:'Papier cuisson',       cat:'Entretien', emoji:'📄', synonymes:['papier sulfurisé','papier parchemin'], rayon:'Entretien' },
  { id:'p227', nom:'Lingettes désinfectantes',cat:'Entretien',emoji:'🧽',synonymes:['lingettes ménagères','lingettes nettoyantes'], rayon:'Entretien' },
  { id:'p228', nom:'Gants ménage',         cat:'Entretien', emoji:'🧤', synonymes:['gants caoutchouc','gants protection'], rayon:'Entretien' },
  { id:'p229', nom:'Sel pour lave-vaisselle',cat:'Entretien',emoji:'🧂',synonymes:['sel adoucisseur','sel régénérant'], rayon:'Entretien' },
  { id:'p230', nom:'Pierre blanche',       cat:'Entretien', emoji:'🧽', synonymes:['crème à récurer'], rayon:'Entretien' },

  /* ===== BÉBÉ & ENFANT ===== */
  { id:'p231', nom:'Couches taille 1',     cat:'Bébé', emoji:'👶', synonymes:['couche bébé','pampers','huggies'], rayon:'Bébé' },
  { id:'p232', nom:'Couches taille 2',     cat:'Bébé', emoji:'👶', synonymes:['couches T2'], rayon:'Bébé' },
  { id:'p233', nom:'Couches taille 3',     cat:'Bébé', emoji:'👶', synonymes:['couches T3'], rayon:'Bébé' },
  { id:'p234', nom:'Couches taille 4',     cat:'Bébé', emoji:'👶', synonymes:['couches T4'], rayon:'Bébé' },
  { id:'p235', nom:'Lingettes bébé',       cat:'Bébé', emoji:'🧴', synonymes:['lingette bébé','pampers sensitive'], rayon:'Bébé' },
  { id:'p236', nom:'Lait infantile 1er âge',cat:'Bébé',emoji:'🍼', synonymes:['lait bébé','préparation nourrisson'], rayon:'Bébé' },
  { id:'p237', nom:'Lait infantile 2e âge', cat:'Bébé',emoji:'🍼', synonymes:['lait 2ème âge'], rayon:'Bébé' },
  { id:'p238', nom:'Petits pots bébé',     cat:'Bébé', emoji:'🥕', synonymes:['pot bébé','purée bébé'], rayon:'Bébé' },
  { id:'p239', nom:'Crème change bébé',    cat:'Bébé', emoji:'🧴', synonymes:['crème bébé','liniment'], rayon:'Bébé' },
  { id:'p240', nom:'Jeu de société',       cat:'Bébé', emoji:'🎮', synonymes:['monopoly','scrabble','puissance 4','trivial pursuit'], rayon:'Jeux & Jouets' },
  { id:'p241', nom:'Cartes à jouer',       cat:'Bébé', emoji:'🎴', synonymes:['uno','jeu de cartes'], rayon:'Jeux & Jouets' },
  { id:'p242', nom:'Puzzle',               cat:'Bébé', emoji:'🧩', synonymes:['puzzle 500 pièces','puzzle 1000'], rayon:'Jeux & Jouets' },
  { id:'p243', nom:'Lego',                 cat:'Bébé', emoji:'🧱', synonymes:['briques lego'], rayon:'Jeux & Jouets' },
  { id:'p244', nom:'Playmobil',            cat:'Bébé', emoji:'🧸', synonymes:[], rayon:'Jeux & Jouets' },
  { id:'p245', nom:'Pâte à modeler',       cat:'Bébé', emoji:'🎨', synonymes:['play-doh'], rayon:'Jeux & Jouets' },
  { id:'p246', nom:'Crayons de couleur',   cat:'Bébé', emoji:'✏️', synonymes:['crayons','faber castell'], rayon:'Librairie / Papeterie' },
  { id:'p247', nom:'Feutres',              cat:'Bébé', emoji:'🖊️', synonymes:['marqueur','feutre coloriage'], rayon:'Librairie / Papeterie' },
  { id:'p248', nom:'Peluche',              cat:'Bébé', emoji:'🧸', synonymes:['doudou','nounours'], rayon:'Jeux & Jouets' },

  /* ===== ANIMALERIE ===== */
  { id:'p249', nom:'Croquettes chien',     cat:'Animalerie', emoji:'🐕', synonymes:['nourriture chien','purina','pedigree'], rayon:'Animalerie' },
  { id:'p250', nom:'Pâtée chien',          cat:'Animalerie', emoji:'🐕', synonymes:['boîte chien','pâtée chien'], rayon:'Animalerie' },
  { id:'p251', nom:'Croquettes chat',      cat:'Animalerie', emoji:'🐱', synonymes:['nourriture chat','royal canin','purina one'], rayon:'Animalerie' },
  { id:'p252', nom:'Pâtée chat',           cat:'Animalerie', emoji:'🐱', synonymes:['boîte chat','whiskas','felix'], rayon:'Animalerie' },
  { id:'p253', nom:'Litière chat',         cat:'Animalerie', emoji:'🐱', synonymes:['litière'], rayon:'Animalerie' },
  { id:'p254', nom:'Friandises chien',     cat:'Animalerie', emoji:'🦴', synonymes:['os','récompense chien'], rayon:'Animalerie' },
  { id:'p255', nom:'Antiparasitaire',      cat:'Animalerie', emoji:'💊', synonymes:['frontline','antipuce','vermifuge'], rayon:'Animalerie' },

  /* ===== DIVERS & PRATIQUE ===== */
  { id:'p256', nom:'Piles AA',             cat:'Divers', emoji:'🔋', synonymes:['piles aa','lr6'], rayon:'Bazar / Électronique' },
  { id:'p257', nom:'Piles AAA',            cat:'Divers', emoji:'🔋', synonymes:['piles aaa','lr03'], rayon:'Bazar / Électronique' },
  { id:'p258', nom:'Ampoule LED',          cat:'Divers', emoji:'💡', synonymes:['ampoule','ampoule e27','ampoule e14'], rayon:'Bazar / Électronique' },
  { id:'p259', nom:'Scotch transparent',   cat:'Divers', emoji:'📎', synonymes:['ruban adhésif','scotch'], rayon:'Librairie / Papeterie' },
  { id:'p260', nom:'Colle',               cat:'Divers', emoji:'🔧', synonymes:['super glue','colle universelle','bostik'], rayon:'Bazar / Électronique' },
  { id:'p261', nom:'Papier imprimante A4', cat:'Divers', emoji:'📄', synonymes:['feuilles a4','ramette'], rayon:'Librairie / Papeterie' },
  { id:'p262', nom:'Post-it',             cat:'Divers', emoji:'📋', synonymes:['notes autocollantes','mémos'], rayon:'Librairie / Papeterie' },
  { id:'p263', nom:'Stylo bille',          cat:'Divers', emoji:'🖊️', synonymes:['bic','stylo'], rayon:'Librairie / Papeterie' },
];

/* ---------- Index de recherche ---------- */

const PRODUITS_INDEX = PRODUITS.map(p => ({
  ...p,
  _cle: [p.nom, ...p.synonymes].join(' ').toLowerCase()
}));

/* Retourne les produits dont le nom ou un synonyme contient `q`, limité à `max`.
   Tri : les correspondances en début de nom passent devant. */
function chercherProduit(q, max = 5) {
  if (!q || q.length < 2) return [];
  const terme = q.toLowerCase().trim();
  const resultats = PRODUITS_INDEX.filter(p => p._cle.includes(terme));
  resultats.sort((a, b) => {
    const aDebut = a.nom.toLowerCase().startsWith(terme) ? 0 : 1;
    const bDebut = b.nom.toLowerCase().startsWith(terme) ? 0 : 1;
    return aDebut - bDebut;
  });
  return resultats.slice(0, max);
}

window.PRODUITS = PRODUITS;
window.chercherProduit = chercherProduit;
